name: SolSolHigh-FE Deploy

on:
    push:
        branches: feat/#50-user-api

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # stage_1 : checkout
            - name: Checkout
              uses: actions/checkout@v4.1.7

            # stage_2 : docker build setting
            - name: Docker Build Setting
              uses: docker/setup-buildx-action@v3.6.1

            # stage_3 : docker hub login
            - name: Docker Hub Login
              uses: docker/login-action@v3.3.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}

            # stage_4 : docker image build and push
            - name: Docker Image Build and Push
              run: |
                  cd ssh-web
                  echo docker image build
                  docker build -t ${{ secrets.DOCKERHUB_USER }}/ssh-web:latest --build-arg API_BASE_URL=${{ secrets.API_BASE_URL }} .
                  echo docker image push
                  docker push ${{ secrets.DOCKERHUB_USER }}/ssh-web:latest

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            # stage : ssh
            - name: SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  script: |
                      echo docker image pull
                      sudo docker pull ${{ secrets.DOCKERHUB_USER }}/ssh-web:latest
                      echo docker stop & rm
                      sudo docker stop ssh-web
                      sudo docker rm ssh-web
                      echo docker run
                      sudo docker run -d --name ssh-web -p 80:80 -p 443:443 -v /etc/ssl/solsol-high:/etc/ssl/solsol-high ${{ secrets.DOCKERHUB_USER }}/ssh-web:latest
