name: SolSolHigh-FE Deploy

on:
    push:
        branches: feat/#68-quiz-promise-account

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            # stage : ssh
            - name: SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SSH_KRO_HOST }}
                  username: ${{ secrets.SSH_KRO_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  script: |
                      cd ~/solsol-high
                      ./static.sh feat/#68-quiz-promise-account
